### ISSUE TITLE
Fixing typos and enhancing documentation 

### ISSUE THREAD

**Issue by sanikaahadap** [Recode-Hive/Scrape-ML#10]
Under GSSoC'24, I would like to contribute to this repository by working on the readability of the contents. I am also analyzing the other files of the repository. Please assign this task to me.

**Comment by Jexa07** [comment]
Hello Sir,
I'd love to tackle the "Fixing typos & docs" issue. I've already begun analyzing the repository's files to identify areas for improvement in readability.  My skills in proofreading and documentation make me confident that I can effectively address the typos and enhance the clarity of the content.

**Comment by Tanu-120** [comment]
Hello Sir, I would love to contribute to this project and help make it even better. I have a strong proficiency in machine learning and Python, and I'm eager to apply my skills to tackle some of the tasks or issues in the project. I'm excited about the opportunity to collaborate with you and the rest of the community on this project.

**Comment by Abdul-Mannan-17** [comment]
Hello Sir,
I'd love to tackle the "Fixing typos & docs" issue. I'm eager to apply my skills to tackle some of the tasks or issues in the project. Please assign this task to me.

**Comment by Shar-03** [comment]
Hi, greetings of the day. I am a contributor at GirlScript Summer of Code. I would like to contribute to your project by working on this issue as my writing skills are good and think that my skills could help the documentation enhancement process. iwould be very grateful to be assigned with this issue.
Regards,
Sharvari Wakhare

**Comment by devidutta-learn** [comment]
I found two typos : 

**1.** **Scrapping vs. Scraping:** There's an inconsistency in spelling "scraping." It's spelled correctly as "scraping" in the first sentence but misspelled as "scrapping" in other places.

**2.** **Semi-supervised-sequence-learning-Project:** This appears multiple times with a hyphen (-) before "Project". While it's not technically incorrect, it might be better for readability to keep it as "Semi-supervised sequence learning project".

**Comment by devidutta-learn** [comment]
> I found two typos :
> 
> **1.** **Scrapping vs. Scraping:** There's an inconsistency in spelling "scraping." It's spelled correctly as "scraping" in the first sentence but misspelled as "scrapping" in other places.
> 
> **2.** **Semi-supervised-sequence-learning-Project:** This appears multiple times with a hyphen (-) before "Project". While it's not technically incorrect, it might be better for readability to keep it as "Semi-supervised sequence learning project".

Please consider assigning me to this task
