### ISSUE TITLE
MOvie recommendation system with streamlit

### ISSUE THREAD

**Issue by Navyazitya** [Recode-Hive/Scrape-ML#105]
Sir.. @sanjay-kv I would like to create a movie recommendation and also would like to create a user friendly interface using streamlit. 
This would increase the adaptibility and the usage of the project.. I would like to work on this issue sir.. Can you pleaseee assign me this issue and label this.. I would complete this issue and raise a PR very soon..

**Comment by sanjay-kv** [comment]
This is already done.  https://github.com/Recode-Hive/Scrape-ML/tree/main/Web_app
