### ISSUE TITLE
Redesign README Image 

### ISSUE THREAD

**Issue by me-shweta** [Recode-Hive/Scrape-ML#109]
@sanjay-kv I am Shweta. As part of GSSOC'24, I'm keen on enhancing the image for **IMDB Movie Review Scraping** with better color choices to make it more visually appealing. Assign me this task!

**Referenced Image** ( The image I am talking about )
<img width="550" alt="scrap" src="https://github.com/Recode-Hive/Scrape-ML/assets/119609866/26ddebc6-b88e-446d-ba38-e44cd920c1de">

**Comment by me-shweta** [comment]
@sanjay-kv I have created some designs. Here they are. 
![1](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/15e1ad01-0424-47e8-b201-0c4432b5de9a)
![2](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/ed979356-693f-4978-87c6-78977684131e)
![3](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/33d801ca-eae1-46da-9eec-0517797a13d6)
![4](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/febc17c6-f492-496c-ab8b-f0385a10dc73)
![5](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/f9044cdb-9c3c-4e4e-8819-6cb3dbda8d24)
![6](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/49579c4c-8d1b-4f0d-bcc1-63c4e2db884b)
![7](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/e180061b-dae3-4e58-ba04-0f3a83f4d80c)
![8](https://github.com/Recode-Hive/Scrape-ML/assets/119609866/cd0ce4d6-ba60-4bff-bc24-9a8ccd842df6)

**Let me know which design suits you best and if there are any changes you would like to make.**

**Comment by sanjay-kv** [comment]
Thanks for the same

**Comment by me-shweta** [comment]
Most welcome! But can you clarify which design you liked the most?

**Comment by sanjay-kv** [comment]
![image](https://github.com/Recode-Hive/Scrape-ML/assets/30715153/f65aac04-2814-43f7-b3b5-9decd470e7f7)

This look fine can you remove the 3000 reviews on the first line

**Comment by sanjay-kv** [comment]
sure i can merge your code without review. once you get badge let me know I'm planning to make a video to teach people.

**Comment by me-shweta** [comment]
@sanjay-kv A video to teach people? Could you explain a bit more?

**Comment by sanjay-kv** [comment]
thats not relevant once you get the github achievement badge let me know here. send me PR request.

**Comment by me-shweta** [comment]
okay!

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.
