### ISSUE TITLE
Correction needed in README file.

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Recode-Hive/Scrape-ML#11]
There are several typos in the README file that need to be corrected. Additionally, in some places, the word "scrap" is used instead of "scrape," which changes the intended meaning. I propose to correct these errors to improve the clarity and accuracy of the documentation. I would like correct these under GSSOC'24. Please assign this to me. Thank you!!

**Comment by devidutta-learn** [comment]
I found these two typos in the README file:-

**1. Scrapping vs. Scraping:** There's a misspelling of "scraping" in the first line. It should be spelled as "scraping" (with one "p").

**2. Semi-supervised-sequence-learning-Project:** This appears multiple times with a hyphen (-) before "Project". While it's not technically incorrect, it might be better for readability to keep it as "Semi-supervised sequence learning project".

**Comment by devidutta-learn** [comment]
> I found these two typos in the README file:-
> 
> **1. Scrapping vs. Scraping:** There's a misspelling of "scraping" in the first line. It should be spelled as "scraping" (with one "p").
> 
> **2. Semi-supervised-sequence-learning-Project:** This appears multiple times with a hyphen (-) before "Project". While it's not technically incorrect, it might be better for readability to keep it as "Semi-supervised sequence learning project".

Please consider assigning me to this task

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of updating your README section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. 
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
