### ISSUE TITLE
Filtering the movie tags and movie URLS

### ISSUE THREAD

**Issue by yashwe0** [Recode-Hive/Scrape-ML#12]
Hello, I'm Yashvi, a contributor in GGSoc'24. I would like you to assign me the issue of number of urls and tags displayed does not matches there count as mentioned in the string. It says "displaying 10 tags" however only  2 are getting returned.

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project, particularly as a GSSOC'24 contributor, leveraging my skills and expertise to address the current challenges swiftly and effectively. Please assign me tasks that align with my abilities, and I will ensure timely resolution while upholding the project's standards and goals.

**Comment by Blackphoenix-15** [comment]
@sanjay-kv i would like to highlight an issue here: the variable names tag_count are being reused, which could lead to the error so we can try renaming one of the tag_count variables in the check_tags function to avoid overwriting the function name.
Also, I suggest an optimization to avoid multiple calls to string.count() and string.replace() within the tag_count function. Instead, we can iterate through the string once to count and remove all occurrences of tags. 
**I would like to fix these, so please allow me to work on it.**

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. 
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by yashwe0** [comment]
@sanjay-kv Thankyou for assigning me with the issue.

**Comment by yashwe0** [comment]
@sanjay-kv  Thankyou for assigning me with this issue.

**Comment by yashwe0** [comment]
@sanjay-kv how do i create a branch under this issue, i have made changes to the cloned repo in VS code
