### ISSUE TITLE
Streamlit app viz issues

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Scrape-ML#125]
Need to change this. the  viz is not working

**Screenshots**
![image](https://github.com/Recode-Hive/Scrape-ML/assets/30715153/a5489124-c949-4133-8b6c-3cfff1d32a0f)

**Smartphone (please complete the following information):**

**Comment by taquiansari** [comment]
Please assign me this issue. I am confident to resolve it.

**Comment by revanth1718** [comment]
sir, user should upload the csv file that contains review column because our app is to analyze the reviews and classify them as positive or negative.

**Comment by sanjay-kv** [comment]
@revanth1718 what csv file you have used, can u attach here. the csv file I upload didn't work as expected.

**Comment by revanth1718** [comment]
[reviews.csv](https://github.com/Recode-Hive/Scrape-ML/files/15420868/reviews.csv)

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by Khushijai** [comment]
Please assign this issue to me . I am a contributor in GSSOC'24.
