### ISSUE TITLE
Function Addition-SENTIMENT ANALYSIS

### ISSUE THREAD

**Issue by Shivani0230** [Recode-Hive/Scrape-ML#13]
I would like to enhance our movie review scraping project by adding sentiment analysis functionality. This will allow us to categorize each review as positive, negative, or neutral, providing valuable insights into the overall sentiment towards specific movies. Please assign this issue to me, I will try my best to enhance the project functionality.

**Comment by Soubeer** [comment]
hello @Shivani0230 , I have been doing ML/DL tasks for over a year now, Did an internship and some projects and this task looks familiar to what I might have done.I would like to try this issue out and hopefully get it done real soon.Although I do have some doubts on this task regarding which dataset to use among the given ones,hoping I get the chance to talk it out and solve out this issue..
Thanks..

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project, particularly as a GSSOC contributor, leveraging my skills and expertise to address the current challenges swiftly and effectively. Please assign me tasks that align with my abilities, and I will ensure timely resolution while upholding the project's standards and goals.

**Comment by Shivani0230** [comment]
ok sir @sanjay-kv and please give the level to my issue

**Comment by sanjay-kv** [comment]
Done. Maybe while review i can upgrade the level by seeing the effort.

**Comment by Shivani0230** [comment]
Task done
