### ISSUE TITLE
Scraping the GSSOC website

### ISSUE THREAD

**Issue by saikuladeepgithub** [Recode-Hive/Scrape-ML#130]
Hi sir,I want to scrape the projects page of gssoc24,could you please assign it to me sir.

**Comment by Samriddha49** [comment]
Please assign this issue to me. I'm a GSSOC'24 Contributor

**Comment by saikuladeepgithub** [comment]
I am doing it,please give me one day time sir

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.

**Comment by khushi-98** [comment]
hello @sanjay-kv 
I am well-equipped to handle this issue as I have successfully resolved similar problems in the past. Please assign it to me.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. 
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

Feel free to create new issue, I will assign to you
