### ISSUE TITLE
Designing A Logo For Scrape-ML

### ISSUE THREAD

**Issue by MehtabAsHellic** [Recode-Hive/Scrape-ML#131]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by sanjay-kv** [comment]
Could you raise simillar issue on stackoverflow repo in same org

**Comment by MehtabAsHellic** [comment]
> Could you raise simillar issue on stackoverflow repo in same org

give me the stackoverflow link please

**Comment by sangati12** [comment]
Hello Sangati here,
I would like to help design logo for Scrape -ML kindly assign me

**Comment by Samriddha49** [comment]
Please assign this issue to me. I'm a GSSOC'24 Contributor

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.
