### ISSUE TITLE
Addition of sentimental analysis using amazon reviews

### ISSUE THREAD

**Issue by yashwe0** [Recode-Hive/Scrape-ML#135]
We can add sentimental analysis in python using the dataset of amazon reviews: It would help us to check whether the review is positive or negative using NLTK basis and Plotting vader results, Second step is Roberta Pretrained Model, third step to Combine and Compare.

**Comment by Samriddha49** [comment]
Please assign this issue to me. I'm a GSSOC'24 Contributor

**Comment by RiaKabra** [comment]
Kindly assign this issue to me as I have a fair idea of how to go about the same, I have past experience with machine learning models and can provide the desired outcome.

**Comment by Khushijai** [comment]
please assign this issue to me . I am a contributor in GSSOC'24

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.
