### ISSUE TITLE
[Feature}Addition of Gui interface for Smart select feature extraction

### ISSUE THREAD

**Issue by litesh1123** [Recode-Hive/Scrape-ML#139]
**Describe the bug**
Smart select feature is all about extraction of text from image ,but there are many still issues to be addressed like while extraction text from image user need to mention what language it is English or any other ,what characteristics he/she want to extract ,image selection , interactive interface where extracted text will be shown.

Technologies used would be  :-
 tikinter for making gui interface
>pre processing of image

**Additional context**
>it will make more interactive
>user friendly
>increased performance as user can optimize with selection

**Comment by sanjay-kv** [comment]
Do you have a screenshot how it look like

**Comment by litesh1123** [comment]
@sanjay-kv sir I will make interface I haven't started work if assigned I will make simple interface with buttons and input bar for user inputs

**Comment by litesh1123** [comment]
![SmartSelect_20240526_123909_Google](https://github.com/Recode-Hive/Scrape-ML/assets/139573484/47df3086-02f5-4b7a-bb0b-4b2e03e8a8bd)
Demo Sir it can be made something like this

**Comment by litesh1123** [comment]
@sanjay-kv please assign me this issue sir
