### ISSUE TITLE
issue in code [scrapping.py}

### ISSUE THREAD

**Issue by kairveeehh** [Recode-Hive/Scrape-ML#14]
@sanjay-kv  in the amazon scrapping folder is we carefully analyze there is a bug or error to be fixed -  the name_list variable is referenced inside the product_listing function without being passed as an argument or defined as a global variable within the function scope.  I would like to fix this issue 
## please assign the issue under gssoc'24

**Comment by Blackphoenix-15** [comment]
@sanjay-kv In scrapping.py, I analyzed that in the code, Variable name_list is not being defined within the product_listing function. Since name_list is defined outside the function, it is not accessible within the function's scope.
I would like to fix this, so please assign this issue to me.

**Comment by sanjay-kv** [comment]
Assigned to you @kairveeehh 
Issue will be assigned to Only 1 person ...FCFS basis.
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by khushikunte** [comment]
Hii.I would like to work on this issue .Please assign me this under GSSOC'24

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can take this up under GSSoC'24. Lemme know. :)

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
