### ISSUE TITLE
Update README.md : Redundant Cloning Instructions

### ISSUE THREAD

**Issue by pearll12** [Recode-Hive/Scrape-ML#144]
In the installation guide in README.md, the instructions for cloning the repository to local machine using both methods - SSH and HTTPS are not clearly differentiated and might confuse new contributors. 
Since it's my first issue and the change seems minimal, I'd like to take this on if you assign the issue to me. Thanks!

**Comment by pearll12** [comment]
@sanjay-kv I have made a pull request #145. Kindly look into it.

**Comment by pearll12** [comment]
@sanjay-kv Please add gssoc24 label since my contribution has not been added to the leaderboard

**Comment by sanjay-kv** [comment]
gssoc will do. we follw gssoc as important label

**Comment by pearll12** [comment]
@sanjay-kv sir I can't see my contribution on the leaderboard, will this contribution not be considered?
