### ISSUE TITLE
Add a learn.md file

### ISSUE THREAD

**Issue by debangi29** [Recode-Hive/Scrape-ML#146]
**Describe the bug**
# The learn.md file is missing

**Expected behavior**
## Learn.md file is a compulsory file which must be added according to Gssoc rules.
**Screenshots**
![image](https://github.com/Recode-Hive/Scrape-ML/assets/117537653/2689ba7a-7047-4bf3-98e8-ba54c239a2f0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
