### ISSUE TITLE
 Enhance Streamlit app with Lottie animation and HTML styling

### ISSUE THREAD

**Issue by SurajSanap** [Recode-Hive/Scrape-ML#148]
The IMDb Movie Review Analysis and Recommendation System Streamlit app could benefit from enhancements to improve user engagement and visual appeal. This issue proposes adding a Lottie animation and implementing HTML styling to achieve these objectives.

### Proposed Changes:
Integrate a Lottie animation into the app using the streamlit_lottie library to create a more dynamic and engaging user experience.
Enhance the HTML styling of the app, including the title, upload section, and error messages, to improve aesthetics and usability.

### Expected Benefits:
Increased user engagement: The addition of a Lottie animation will make the app more visually appealing and interactive, encouraging users to explore its features.
Enhanced aesthetics: HTML styling improvements will result in a more polished and professional appearance, contributing to a positive user experience.
Additional Notes:

It's essential to ensure that the Lottie animation and HTML styling are implemented in a way that maintains the app's accessibility and responsiveness across different devices and screen sizes.
Testing will be necessary to verify that the enhancements function correctly and do not introduce any regressions in app functionality.

Please assign this issue to me under Gssoc.

**Comment by SurajSanap** [comment]
PR raised #149

**Comment by SurajSanap** [comment]
Issue solved: #149

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will make the UI visually appealing and nyc.
