### ISSUE TITLE
lack f documentation

### ISSUE THREAD

**Issue by kairveeehh** [Recode-Hive/Scrape-ML#15]
@sanjay-kv  I would liek to add to the documentation of the moviescraper,ipynb file in the code base , fixingt the typos like soap->soup etc which i have noticed and also provide a readable and explanatory lines to functions 

## please assign under ggsoc'24

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project, particularly as a GSSOC contributor, leveraging my skills and expertise to address the current challenges swiftly and effectively. Please assign me tasks that align with my abilities, and I will ensure timely resolution while upholding the project's standards and goals.

**Comment by sanjay-kv** [comment]
Hi @kairveeehh I assigned you can start working on it.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.
