### ISSUE TITLE
Adding a Code of Conduct md file

### ISSUE THREAD

**Issue by sanskritilabroo** [Recode-Hive/Scrape-ML#152]
The repository currently lacks a code of conduct file, which is very necessary to provide a set of guidelines for GSSOC'24 potential contributors on how to engage with the project effectively. This will be useful to document clearly any rules and regulations to follow before diving into the project. Although this issue has been mentioned before, it has not been solved till now.

Could you please assign this issue to me under GSSOC 24. @sanjay-kv

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
