### ISSUE TITLE
ADD CLUSTERING FOR PRODUCT DATA

### ISSUE THREAD

**Issue by Soubeer** [Recode-Hive/Scrape-ML#16]
Hey there, I have looked into the datasets used in the project and found that clustering the product listings along with the Silhouette Score would be a great help for future processing and analysis of the same for deeper dive into the information.I have been doing ML/DL tasks for quite a while now and have made projects and done an internship on the same domain.

I would like to take this issue under GSSOC'24 and solve it real quick.

Hope I make it to your sight.

Thanks..

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project. Kindly assign me this tasks as it aligns with my skills and expertise.

**Comment by sanjay-kv** [comment]
assigned to you @Soubeer 
Issue will be assigned to Only 1 person ...FCFS basis.
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.
