### ISSUE TITLE
Streamlit app is not working

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Scrape-ML#160]
https://scrape-review-analysis.streamlit.app/

**Comment by revanth1718** [comment]
sir, once reboot the app or redeploy the app .

**Comment by sanjay-kv** [comment]
sure

**Comment by sanjay-kv** [comment]
![image](https://github.com/Recode-Hive/Scrape-ML/assets/30715153/794d2142-fd59-43d8-a99e-cae7c2387cc5)
main module file missing @revanth1718

**Comment by revanth1718** [comment]
somebody changed the main module steeamlit_app.py into Homepage.py.

**Comment by sanjay-kv** [comment]
thanks
