### ISSUE TITLE
File missing 'Similarity.pkl'

### ISSUE THREAD

**Issue by SurajSanap** [Recode-Hive/Scrape-ML#166]
**Describe the bug**
There is an file missing error:  E:\SRS\CODES\GSOC\Scrape-ML\Web_app\pages\2_Movie_Recommendation.py

**To Reproduce**
1. Go to Scrape-ML\Web_app
2. run streamlit app Home.py
3. Go to Movie_Recommendation page

**Expected behavior**
It should run properly

**Screenshots**
![Screenshot 2024-06-04 100501](https://github.com/Recode-Hive/Scrape-ML/assets/101057653/5c92a05d-8b71-41ca-aa42-523594463740)

I have already generated it. **You can assign this issue to me**. Thank you.

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.

**Comment by shashbh18** [comment]
Please assign this to me
