### ISSUE TITLE
Adding Contribution Images and Animating Emojies in Readme.md file

### ISSUE THREAD

**Issue by Harshitmishra001** [Recode-Hive/Scrape-ML#168]
### **Describe the bug**
**Adding Contiributions images to Readme.md file**
**Animating Emojis in The readme.md file**

### **Screenshots**
**I want To add something like this**
![Screenshot 2024-06-04 124526](https://github.com/Recode-Hive/Scrape-ML/assets/131855565/bb8cb8f6-5bc9-4f6a-893d-c54231e2a44a)

**Comment by Harshitmishra001** [comment]
@sanjay-kv Can you please review it

**Comment by Taranpreet10451** [comment]
@sanjay-kv Please assign this to me.

**Comment by Harshitmishra001** [comment]
@Taranpreet10451 This is already completed i forgot to close this issue
