### ISSUE TITLE
Sentimental Analysis

### ISSUE THREAD

**Issue by MahimaRamireddy** [Recode-Hive/Scrape-ML#17]
Hello I am Mahima Ramireddy contributor of GSSoC '24. I'd like to take on the task of enhancing our movie review scraping project by integrating sentiment analysis. This addition will enable us to classify each review as positive, negative, or neutral, providing valuable insights into the general sentiment surrounding particular movies. Please assign this task to me, and I'll work on improving the project's functionality.

**Comment by Basma2423** [comment]
Can you assign it to me? @SrijanShovit

Full name: **Basma Mahmoud**
GitHub Profile Link: [Basma2423](https://github.com/Basma2423)
Email ID: mayarbasma2423@gmail.com
Approach for this Project: Tensorflows's,NLTK and other NLP libraries
What is your participant role? (Mention the Open Source program): **GSSoC-2024** participant

Can you add the label for **GSSoC**, please?
Thanks.

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project. Kindly assign me this tasks as it aligns with my skills and expertise.

**Comment by SrijanShovit** [comment]
> Can you assign it to me? @SrijanShovit
> 
> Full name: **Basma Mahmoud** GitHub Profile Link: [Basma2423](https://github.com/Basma2423) Email ID: [mayarbasma2423@gmail.com](mailto:mayarbasma2423@gmail.com) Approach for this Project: Tensorflows's,NLTK and other NLP libraries What is your participant role? (Mention the Open Source program): **GSSoC-2024** participant
> 
> Can you add the label for **GSSoC**, please? Thanks.

It's not my project. Please have a look before commenting on a repo.

**Comment by sanjay-kv** [comment]
Assigned to you @MahimaRamireddy 
Issue will be assigned to Only 1 person ...FCFS basis.
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
