### ISSUE TITLE
TypeError: WebDriver ._ init_() got an unexpected keyword argument 'executable_path'

### ISSUE THREAD

**Issue by SurajSanap** [Recode-Hive/Scrape-ML#171]
**Describe the bug**

Page; Scarper.py

TypeError: WebDriver ._ init_() got an unexpected keyword argument 'executable_path'
Traceback:
exec (code, module .__ dict __ )
driver = webdriver.Chrome(options=options,executable_path=DRIVER_PATH)

![Screenshot 2024-06-06 135400](https://github.com/Recode-Hive/Scrape-ML/assets/101057653/b41b18bd-8acc-47e3-a654-44a875dcaecb)

**Comment by SurajSanap** [comment]
#172 PR created

**Comment by Taranpreet10451** [comment]
@sanjay-kv Can you please assign this to me.
