### ISSUE TITLE
Add callbacks to handle overfitting

### ISSUE THREAD

**Issue by Aditi22Bansal** [Recode-Hive/Scrape-ML#177]
**Describe the bug**
While callbacks like EarlyStopping and ReduceLROnPlateau are essential, incorrect configuration might lead to unexpected behavior. Ensuring the parameters for these callbacks are correctly set.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Aditi22Bansal** [comment]
@sanjay-kv 
Kindly assign me this issue

**Comment by sanjay-kv** [comment]
as we have multiple files over here, which files you are mentioning the changes.

**Comment by Aditi22Bansal** [comment]
@sanjay-kv 
Movie review scrapping one
