### ISSUE TITLE
Web scraping using OCR software .

### ISSUE THREAD

**Issue by litesh1123** [Recode-Hive/Scrape-ML#18]
Problem - Data scrapped from the website would be insufficient and inaccurate with only usage of selenium and beautiful soap for scrapping. 

solution- I propose the usage of OCR software called Tesseract , which would extract text from images , selenium has a feature where it can take couple of screenshots of website  ,this will be given to tesseract for extraction.

Please assign me  this issue

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project. Kindly assign me this tasks as it aligns with my skills and expertise.

**Comment by sanjay-kv** [comment]
assigned to you @litesh1123 
Issue will be assigned to Only 1 person ...FCFS basis.
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by litesh1123** [comment]
@sanjay-kv  thank you sir

**Comment by lassmara** [comment]
Please assign me this issue
