### ISSUE TITLE
Price Comparison Tool with Recommendation System

### ISSUE THREAD

**Issue by ShaikArshidBanu** [Recode-Hive/Scrape-ML#186]
**Description:**

Develop a comprehensive price comparison tool that gathers pricing information from multiple e-commerce websites (e.g., Flipkart and Amazon) and utilizes machine learning techniques to recommend the best deals based on historical price trends and user preferences.

**Features:**
- **Web Scraping:** Scrapes product prices from e-commerce websites (Flipkart and Amazon) using Scrapy.
- **Data Preprocessing:** Cleans and processes the scraped data to ensure consistency and accuracy.
- **Historical Price Simulation:** Simulates historical price trends by introducing random variations to the current prices.
- **Recommendation System:** Employs collaborative filtering with K-Nearest Neighbors (KNN) to suggest the best deals based on historical price data.

@sanjay-kv I am a GSSOC'24 Contributor and would like to work on this issue,please assign this issue to me.

**Comment by khushi-igupta** [comment]
Hello @ShaikArshidBanu , I am GSSOC'24 contributor. Can you assign me this issue?

**Comment by sanjay-kv** [comment]
this is not related to this repo.
