### ISSUE TITLE
Make a full test on dataset based on BERT

### ISSUE THREAD

**Issue by Soubeer** [Recode-Hive/Scrape-ML#188]
I would like to propose a new method of analyzing data over the IMDB dataset. BERT (Bidirectional Encoder Representations from Transformers) for analyzing the IMDb movie review dataset. BERT has revolutionized natural language processing (NLP) with its deep bidirectional understanding of text, making it ideal for tasks such as sentiment analysis and review classification.

The task should cover an introduction to BERT, data preprocessing, model training and fine-tuning, evaluation and results, and usage instructions. This will provide a clear, hands-on guide for users to understand and replicate our BERT-based sentiment analysis and classification on the IMDb dataset.

This will have a baseline and BERT workaround difference scale, to showcase the difference between the two approaches.

I would like to take this task under GSSOC'24.

Thank You

**Comment by sanjay-kv** [comment]
I cant assign any label atm , as I need to see the code . you can start working on it.
