### ISSUE TITLE
Scrape NBA stats using selenium and beautifulSoup

### ISSUE THREAD

**Issue by rahulnarayaniitk** [Recode-Hive/Scrape-ML#193]
@sanjay-kv 
Sir, I want to scrape NBA stats of players from basketball reference website using Selenium and beautifulSoup libraries.
Please assign this issue to me.

**Comment by sanjay-kv** [comment]
We only focus on IMDB and reviews. https://github.com/Recode-Hive/machine-learning-repos you can raise this in the repo link given.
