### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by Princegupta101** [Recode-Hive/Scrape-ML#2]
In GSSoC'24, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue. 👍

**Comment by Kirti-Pant** [comment]
Hey, @Princegupta101  I'd like to work on this issue please assign this issue to me.

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project, particularly as a GSSOC contributor, leveraging my skills and expertise to address the current challenges swiftly and effectively. Please assign me tasks that align with my abilities, and I will ensure timely resolution while upholding the project's standards and goals.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by Kirti-Pant** [comment]
I have my built in practice ML projects in my repository please let me know do I have to only describe about software I used to make it ?
