### ISSUE TITLE
Fraudulent Website Detection

### ISSUE THREAD

**Issue by PadmalathaKasireddy** [Recode-Hive/Scrape-ML#206]
Detect fraudulent websites using the Malicious and Benign Websites dataset by analyzing URL characteristics (length, structure), server attributes (location, reputation), and content features (malicious scripts, deceptive information), leveraging machine learning for effective classification.

**Comment by PadmalathaKasireddy** [comment]
Iam a gssoc contributor 2024, i have already worked on the issue.
@sanjay-kv please assign me this issue under gssoc level3
thank you

**Comment by sanjay-kv** [comment]
How come even before assigning you did PR for this?
This is not the right approach.
