### ISSUE TITLE
Add Recommendation system

### ISSUE THREAD

**Issue by akhundubedullah** [Recode-Hive/Scrape-ML#22]
Recommendation System:Build a system to recommend movies or books based on user preferences.

**Comment by sanjay-kv** [comment]
Assigned you the issue @akhundubedullah

**Comment by Tanu-120** [comment]
please assigned this task to me

**Comment by Hetul16** [comment]
I have experience building a movie recommendation system, so I believe I am a perfect candidate for this task.
I am looking forward to contributing to this project.

**Comment by Cheshta17** [comment]
Hi @akhundubedullah , I would like to work on this issue and further can contribute more to this project. Could you please assign it to me?

**Comment by SayantikaLaskar** [comment]
Hi, I would like to contribute to the issue. Please assign me this issue.

**Comment by ajoshi30** [comment]
I'm excited to leverage my experience with recommendation algorithms to develop an effective system that enhances user engagement and satisfaction. Could you please assign me this project?
