### ISSUE TITLE
scraping the items based on the ratings of items

### ISSUE THREAD

**Issue by poojaharihar03** [Recode-Hive/Scrape-ML#27]
1. Further we can scrape the items based on the ratings and 
2. also we can try scraping zomato and swiggy. 

I have worked on web scraping before so willing to work on this idea.
Looking forward to collaborate.

**Comment by sanjay-kv** [comment]
I assigned to you @poojaharihar03 also labelled level 3 which is 45 points.

**Comment by poojaharihar03** [comment]
sure!
