### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [Recode-Hive/Scrape-ML#3]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by Kochurii** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by devidutta-learn** [comment]
I’m eager to contribute to your project by drafting a comprehensive **Code of Conduct**. My experience in community management and policy writing will ensure it’s thorough and inclusive.

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project, particularly as a GSSOC contributor, leveraging my skills and expertise to address the current challenges swiftly and effectively. Please assign me tasks that align with my abilities, and I will ensure timely resolution while upholding the project's standards and goals.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by Priyanshu2631** [comment]
I had already made a code of conduct.md file for this issue, please assign this issue to me such that I can contribute to this project and merge PR

**Comment by officeneerajsaini** [comment]
@sanjay-kv  , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
