### ISSUE TITLE
Make a webpage and show all the visualization and machine learning model results and insights at one place

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Scrape-ML#30]
it is kinda difficult to make the jupter notebook user-friendly and kinda inclusive so making a webpage that include all insights and
By transitioning from Jupyter notebooks to a web interface, users can effortlessly explore data-driven findings, improving comprehension and engagement. This approach democratizes access to valuable insights, fostering a more inclusive and interactive learning environment.please assign this task under GGSOC'24

**Comment by poojaharihar03** [comment]
this is a very good idea !

**Comment by AmrutaJayanti** [comment]
Can you please assign me this task

**Comment by AmrutaJayanti** [comment]
Can you assign me this task @sanjay-kv

**Comment by sanjay-kv** [comment]
@Assigned to you

**Comment by AmrutaJayanti** [comment]
@sanjay-kv a quick question ... Is there any timelimit to PR it .
Where should I include this

**Comment by Shraman-jain** [comment]
@sanjay-kv can you please assign this issue to me I can make a streamlit web app for the Movie data analysis and make a recommendation system as well
