### ISSUE TITLE
Scrapping used car details and price data

### ISSUE THREAD

**Issue by ISmokeData** [Recode-Hive/Scrape-ML#34]
1. Scraping the used car details data , location : Mumbai 
2. Clean raw data 
3. Create analysis dashboard using streamlit
4. Create Web application for used car price prediction model

**All codes with heading and simple explanation**

**Comment by sanjay-kv** [comment]
I suggest not to add in the same ipynb code, as this some different category make your own code file and separate folder for the same. @ISmokeData

**Comment by palayushi293** [comment]
want to work on this issue ,, and i will give my best
Waiting for your response 
best regards
