### ISSUE TITLE
Amazon Scrapping 

### ISSUE THREAD

**Issue by yashwe0** [Recode-Hive/Scrape-ML#36]
We can add basic analysis of dataset therein amazon scrapping and undergo various operations :
1) Data cleaning
2) generate wordscloud
3) Model training, Evaluation, and Prediction
4) Logical Regression

**Comment by amroodh** [comment]
i would like to resolve this issue.
im working as contributor under GSSOC 24

**Comment by Teja-m9** [comment]
hey @sanjay-kv assign this to me 
I'm eager to contribute to the Amazon web scraping project. I came across some Machine Learning approaches that could potentially automate data extraction and handle variations in website structure.  Would there be an opportunity for me to explore this further and see if it could streamline the scraping process?

**Comment by SanskarShrivastava** [comment]
Hii sanjay, I want to contribute in this issue as I have done web scrapping earlier and I will be able to scrap  data efficiently.
Please assign this issue to me

**Comment by Aishu040** [comment]
Hii @sanjay-kv 
 I want to contribute in this issue and I have previous knowledge about this. Please assign this issue to me

**Comment by sreesti07** [comment]
Hi @sanjay-kv 
Please assign this issue to me, I would like to help you. I have previous knowledge of web scrapping.

**Comment by MOHINI1403** [comment]
I would like to contribute on this issue not only scrapping the relevant data like items it would be divided into categories, scraping the dark patterns as it's an e-commerce website and dividing things based on collaborative filtering .
Looking forward to work on this issue
