### ISSUE TITLE
Change the whole dataset

### ISSUE THREAD

**Issue by ldneal** [Recode-Hive/Scrape-ML#42]
Hi sir I check the whole dataset of scrape ML but some error coding in python So I try myself in Colab to just check. Sir Pls Assign Me in this Task

**Comment by ldneal** [comment]
Sir Pls Assign Me In this Project

**Comment by sanjay-kv** [comment]
Hi @ldneal  You need to spesfic about the error you mention, maybe with additional ss will help to understand it better.

**Comment by ldneal** [comment]
OK Sir
