### ISSUE TITLE
Movie Recommender system

### ISSUE THREAD

**Issue by Somya2115** [Recode-Hive/Scrape-ML#51]
We can build a movie recommendation system from the imdb data. I would like to contribute to the project by building a recommender system. Please let me contribute by assigning me this issue and a label. Thank you!
Name- Somya Agarwal
Email Id- agarwal1001poonam@gmail.com

**Comment by sanskritilabroo** [comment]
@Somya2115 Hey, I too was interested in this and wanted to ask if I can help contribute to building this recommender system under GSSOC'24.

**Comment by Somya2115** [comment]
> @Somya2115 Hey, I too was interested in this and wanted to ask if I can help contribute to building this recommender system under GSSOC'24.

Sure 
 My Github: https://github.com/Somya2115

**Comment by Somya2115** [comment]
@sanjay-kv sir can I upload my jupyter notebook on this repository? I am not getting how to contribute through vs code. Can I just upload my jupyter python file(offline mode) on this github repository which I forked?

**Comment by Divyanshi-2211** [comment]
Please assign this issue to me I have already created one of the Movie recommender system so I can contribute to this

**Comment by Amarta113** [comment]
> @sanjay-kv sir can I upload my jupyter notebook on this repository? I am not getting how to contribute through vs code. Can I just upload my jupyter python file(offline mode) on this github repository which I forked?

You can download the notebook, create a branch, add it to the cloned project on VS Code, and submit a PR.
