### ISSUE TITLE
Streamlit webapp

### ISSUE THREAD

**Issue by Shraman-jain** [Recode-Hive/Scrape-ML#56]
Make a streamlit web app to show the Movie analysis and recommendations system. Please assign this to me 
Email - jainshraman1998@gmail.com

**Comment by sanjay-kv** [comment]
Assigned to you @Shraman-jain

**Comment by DevNandini02** [comment]
@sanjay-kv sir i want to work on this. Please assign this task to me.

**Comment by Shraman-jain** [comment]
@DevNandini02 I am already working on it

**Comment by DevNandini02** [comment]
Is this issue closed? If not i would like to work on it @sanjay-kv sir.

**Comment by DevNandini02** [comment]
@sanjay-kv sir why was i assigned then unassigned in 1 hour? Shraman-jain has been working on this issue since past 1 week already.

**Comment by sanjay-kv** [comment]
i can see simillar issue raised before and person already PR it. so I will closing this issue as he kept it stale.

**Comment by Shraman-jain** [comment]
@sanjay-kv sir I was about to fork and upload the web app files I have other submissions as well I have made a scrapper.ipynb file and a streamlit app as well I just am new to open source and was try to fork repo and commit the code please open this issue and give me a day I will fork at commit the code

**Comment by sanjay-kv** [comment]
https://github.com/Recode-Hive/Scrape-ML/tree/main/Web_app

There is already a Streamlit application here, could you check and see anything not as per your development those things can be merged.

**Comment by Shraman-jain** [comment]
Actually the app here is using sentiment analysis for recommending movies which I think is not a right way I am doing it by content based filtering method

**Comment by Shraman-jain** [comment]
@sanjay-kv Sir I have made the necessary changes and created a Main Streamlit app where we are dividing whole thing into two parts one is movie review analysis and other is movie recommendations system. I have made a new app and add the existing streamlit webapp as first part of that app. I have provided screenshots as well in my PR. Please check that and will request you to merge my PR.Thanks
