### ISSUE TITLE
Fake review detection

### ISSUE THREAD

**Issue by viththagi** [Recode-Hive/Scrape-ML#57]
A machine learning model which can predict whether an online review is fraudulent or not. The main idea used to detect the fake nature of reviews is that the review should be computer generated through unfair means. If the review is created manually, then it is considered legal and original.

Detection of fake reviews out of a massive collection of reviews having various distinct categories with each review having a corresponding rating, label i.e. CG(Computer Generated Review) and OR(Original Review generated by humans) and the review text.

Main task is to detect whether a given review is fraudulent or not. If it is computer generated, it is considered fake otherwise not.

**Techniques used:**
Removing punctuation character
Transforming text to lower case
Eliminating stopwords
Stemming
Lemmatizing
Removing digits
**Transformers Used for Text Vectorization, Weighting and Normalization:**
CountVectorizer Bag of Words Transformer
TFIDF(Term Frequency-Inverse Document Frequency) Transformer

I would like to work on these issue

**Comment by sreesti07** [comment]
Could you assign this to me? I'm interested.  I have hands-on Python and Machine Learning.

**Comment by Satyam0775** [comment]
I requested to assign me the issue. @sanjay-kv

**Comment by sanjay-kv** [comment]
Let me know @sreesti07 if you want to collaborate with @Satyam0775

**Comment by Madhusri02** [comment]
@Satyam0775  I will collabrate with @sreesti07 ,

**Comment by sreesti07** [comment]
Yea I am okay to collaborate with @Satyam0775

**Comment by Chandrikajoshi123** [comment]
I am excited to tackle this issue. I requested you to assign me

**Comment by Satyam0775** [comment]
> Yea I am okay to collaborate with @Satyam0775

okey

**Comment by HarshSaini23** [comment]
Hello Sir i am also want to contribute in this issue .
