### ISSUE TITLE
Movie Rating Prediction

### ISSUE THREAD

**Issue by iABn0rma1** [Recode-Hive/Scrape-ML#58]
This project will allow users to predict the movie rating based on factors with the most influence on the ratings, like casting, director, and movie genre.
It will involve data analytics and preprocessing to train the ML model. I propose testing 2-3 models to compare their performance.
Tasks to be performed:
- Analyzing: The most important features influencing the ratings
- Preprocessing: Creating new features and modifying existing ones (handling categorical columns)
- Model Building and Evaluation: Using models like Decision Trees, Random Forests and Neural Network

**Comment by Cralsic123** [comment]
@sanjay-kv @SanjanaBankar My whole profile is based on machine learning, I would very much like to contribute to this issue. Please assign me this issue. Thank you.

**Comment by Vis1hal** [comment]
please assign this to me , I  have already made some many projects like this

**Comment by Satyam0775** [comment]
I requested to assign me the issue. @sanjay-kv

**Comment by psyuktha** [comment]
hey @sanjay-kv I would like to help contributing in this issue ,please assign me

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
