### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by Princegupta101** [Recode-Hive/Scrape-ML#6]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by Kirti-Pant** [comment]
Hello @Princegupta101  I would like to add my projects experience in order to guide various open source contributors . Please assign me this issue under GSSoC'24

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of updating your LEARN section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by kashish-a** [comment]
Hello. I would like to contribute to this issue. Please assign me the project

**Comment by poojaverma9578** [comment]
I am eager to make a meaningful contribution to this project, particularly as a GSSOC contributor, leveraging my skills and expertise to address the current challenges swiftly and effectively. Please assign me tasks that align with my abilities, and I will ensure timely resolution while upholding the project's standards and goals.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by Taranpreet10451** [comment]
@sanjay-kv Sir I would I want to work on this issue.
