### ISSUE TITLE
Contextual and non-contextual vectorization of Data

### ISSUE THREAD

**Issue by Vedantkoppal** [Recode-Hive/Scrape-ML#60]
The data can be converted into more useful data for applying ML and DL algorithms. Making the data more useful and ready made.

Convert the data into more formats using, contextual encoders such as universal sentence encoder, bag of words such as tf-idf and count vectorizer, and other new types of encoding.

This will help programmers to apply their ML and DL algorithms onto already preprocessed data.

In addition to this, we can apply multiple algorithm on the data as to show comparitive analysis on diffrent formats of prepeocessed data

**Comment by Vedantkoppal** [comment]
Could you assign me this issue?
I have worked experience on NLP techniques and I can solve this issue

**Comment by Laxmanpratapsingh** [comment]
I would like to work on this, please assign this to me
