### ISSUE TITLE
Movie Recommender System

### ISSUE THREAD

**Issue by Abhay182005dat** [Recode-Hive/Scrape-ML#62]
As this whole project was about Scrapping stuff i had an idea how about we add a feature called movie recommender system into this project sir?

Also by making this feature there would be many more stuff in this small feature where people can collaborate so i think this will be one of the best major updates sir 

Hence i would request you to assign this role if you give permission to make this feature and integrate into this project

Thank you =D

Abhay :)

**Comment by Abhay182005dat** [comment]
Thank you so much sir...

As a new comer to open source and also a beginner in machine learning how can i ask help if i have any problem like who will be the mentor can i ask..?

Thank you

**Comment by Abhay182005dat** [comment]
I thought I had give up on this project but i thought once again and thought of giving it another chance :').

**Comment by Abhay182005dat** [comment]
Yeah I have a latest dataset of movies and based om that i am creating a basic project as i am a beginner

**Comment by sanjay-kv** [comment]
@Abhay182005dat Sorry for the delay in responding.
@okaditya84 is the mentor for the project.

**Comment by Abhay182005dat** [comment]
Its ohk sir.... :)

**Comment by Navyazitya** [comment]
Sir @sanjay-kv ... could you please assign this to me... I would like to do this...
I already worked on some projects like this and I think I can do this ...

**Comment by sanjay-kv** [comment]
This has been already assigned. Once the assigned person keep the issue stale will assign to you.
