### ISSUE TITLE
clustering movie data from imdb

### ISSUE THREAD

**Issue by merciajeno** [Recode-Hive/Scrape-ML#64]
1.We scrape IMDb data including movie titles, ratings, and summaries.
2.We use TF-IDF vectorization to convert the movie summaries into numerical feature vectors.
3.We apply K-means clustering to group the movies into clusters based on their summaries.
4.We use PCA for dimensionality reduction to visualize the clusters in a 2D space.

**Comment by satwika10** [comment]
I want to scrape data from imdb,prepare the data and apply a suitable clustering algorithm. kindly please assign this project to me under Gssoc'2024.

**Comment by Roverbk** [comment]
I would like to work on this issue. Scraping data and converting to a numerical feature vector and applying K-means and PCA dimensionality reduction.

**Comment by merciajeno** [comment]
> I would like to work on this issue. Scraping data and converting to a numerical feature vector and applying K-means and PCA dimensionality reduction.

Contact me- mercia.jeno@gmail.com as I need some help here

**Comment by sukhadak11** [comment]
want to scrape data from imdb,prepare the data and apply a suitable clustering algorithm. kindly please assign this project to me under Gssoc'2024.

**Comment by merciajeno** [comment]
Hello @roverbk, this issue has been assigned to both of us, so we need to know who is doing what and both of us should do it. So, contact me.

**Comment by Roverbk** [comment]
@sanjay-kv we both have completed the issue individually, @merciajeno did the first two tasks and I did the last two.

**Comment by Roverbk** [comment]
ok

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv  , please assign this issue to me.

**Comment by Roverbk** [comment]
@sanjay-kv since for this issue mercia did PR, I think I am not in leaderboard. What can be done?

**Comment by sanjay-kv** [comment]
technical issue might be you can raise a sample issue and PR mentioning this link. i will merge.
