### ISSUE TITLE
Scrapping Gaming Laptop Specifications and price Data

### ISSUE THREAD

**Issue by ISmokeData** [Recode-Hive/Scrape-ML#67]
1. I can scrap all Gaming Laptop  specification data like brand, processor name, processor generation, graphic card name, graphic card memory etc.
2. I use selenium and beautiful soup tool extract the raw data
3. Clean raw data to useful data

**This data will help to analyze which gaming laptop we can buy in reasonable price with good specification**

**Comment by sanjay-kv** [comment]
This is not required we foucusing on Movie data now
