### ISSUE TITLE
Girlscript Summer of Code Introduction/Tracking

### ISSUE THREAD

**Issue by Princegupta101** [Recode-Hive/Scrape-ML#7]
👋 Hi @Recode-Hive,

I am Prince,web developer Girlscript Summer of Code. I'll be collaborating with you on preparing your repo for GSSoC'24 Program

Why are these changes required?
After Analysing last year's contributions and feedback it would be great for students to have a couple of standard readme files on the repo to understand what the project is all about and some issues detailing what they can contribute. This will help you to see increased engagement in your repository as well.

As mentioned students get a chance to learn step by step, how to build this project as well as invite mentors to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for Girlscript summer of code 2024 on 10th May.

This issue will serve as a tracking issue to track all issues related to GSSoC'24. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat:

- [ ] #2
- [ ] #3 
- [ ] #4
- [ ] #5 
- [ ] #6

**Comment by akshatsingh523** [comment]
I would like to work on this project please reach out to me through my mail akshat05022003@gmail.com

**Comment by shrehs** [comment]
hello @Princegupta101,
I would love to express my intrest, enthusiasum to work on this project. I have worked on some ML projects. I believe I could leverage my learning if able contribute. I am very intrested in the semi- supervised sequence learning.

**Comment by ridhi-ahuja** [comment]
Hello , as a Contributor in GS'SOC 2024 I am looking forward on working and contributing in this project as per my interest .it would enhance and upgrade my technical skills.
I've developed skills in JAVA , C , Java script ,Python , WEB development and basic Machine Learning ,currently under Artificial Intelligence training on implementing AI tools ,exploring more in tech.

**Comment by bhartijoshi04** [comment]
Hello,
This project intrigued my interest, I am highly considering working on this project.
I've developed skills in data analysis, ML, and CNN models.
From this project, I believe I can gain better hands-on experience

**Comment by Kirti-Pant** [comment]
Hey, @Princegupta101  I'd would like to work on this issue in order to contribute on open source please assign this issue to me.

**Comment by ldneal** [comment]
Hello Sir I'm Interested in this project & I would like to do work on this project as a contributor in your project to get skill developed.

**Comment by ldneal** [comment]
Pls Assign me as a mentor

**Comment by Ranit-Bandyopadhyay** [comment]
Hi @Princegupta101  i would like to work on this issue

**Comment by sanjay-kv** [comment]
This is not an issue, you guys can create an issue and start working on it.
