### ISSUE TITLE
Missing Contribute.md file

### ISSUE THREAD

**Issue by Priyanshu2631** [Recode-Hive/Scrape-ML#73]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by LAKSHYA1509** [comment]
Hi Contribute.MD Is a crucial file that contains all the potential information on how to create your own pull request and for new beginners regarding this project and therefore with a knack of content writing 
I would really love working on that and this includes all the contribution guidelines and all the standards of coding with the procedures of how to submit a pull request thus it is very important to have a contributing dot MD file and therefore, 
I would be very very happy if you would assign this task to me I will create all the necessary informations with that contributing dot md file with all the git bash commands and other things so I would really request that can you please assign this task to me under the GSSOC 2024.

**Comment by suhanipaliwal** [comment]
Duplicate issue. Already raised #35
