### ISSUE TITLE
Dectecting outliers using DBSCAN 

### ISSUE THREAD

**Issue by SwarnenduJUIT** [Recode-Hive/Scrape-ML#76]
**Is your feature request related to a problem? Please describe.**
While using k means clutering for https://github.com/Recode-Hive/Scrape-ML/blob/main/clustering%20movie%20review.ipynb we might get outliers . We will now perform DBSCAN and also detect the outliers.

**Describe the solution you'd like**
We will implement DBSCAN and detect the outliers.

**Describe alternatives you've considered**
We will  move any other clustering algorithm.

**Comment by SwarnenduJUIT** [comment]
@sanjay-kv assign me this issue and i will move forward to detect the outliers for the above.

**Comment by Pranali3103** [comment]
@sanjay-kv please assign me this issue , I can work with this.
