### ISSUE TITLE
Adding a cleaned and latest dataset from kaggle

### ISSUE THREAD

**Issue by Abhay182005dat** [Recode-Hive/Scrape-ML#79]
Hello Sir, 

This is regarding Datasets which are major problem while creating machine learning algorithms.Hence i would like to add a new dataset to out Scrape-ML library and after adding i will open another issue about making beginner level projects with that dataset.

Thank you 

Regards

**Comment by sanjay-kv** [comment]
@Abhay182005dat Hi abhay we work on scrapping , we don't use any existing dataset.
