### ISSUE TITLE
[Feature]: Movie Genre Prediction Model

### ISSUE THREAD

**Issue by seeratfatima19** [Recode-Hive/Scrape-ML#92]
I propose to make a movie genre prediction model which will predict the genre of movies parsing the movie summary. I will be doing it using the NLP libraries like nltk most probably.

Please assign this issue to me under the label GSSoC'24

thanks and regards

**Comment by sanjay-kv** [comment]
Please push the file into backlog if you creating sepetate ipynb file

**Comment by seeratfatima19** [comment]
Sorry to bother you Sanjay, I usually make branch and push in that branch.

If there is some other way to push into project backlog, kindly let me know.
Thanks

**Comment by sanjay-kv** [comment]
you create file in your local repo in the back log folder and push it via branch. make sure you pull before push

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.

**Comment by Samik123Mit** [comment]
pls assign me the issue ,i have prior experience with the model.
